version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: 0 12 * * *
    reviewers:
      - akkinoc
    assignees:
      - akkinoc
    labels:
      - type:dependencies
    milestone: 2
  - package-ecosystem: maven
    directories:
      - /
      - /examples/simple-java
      - /examples/simple-kotlin
    schedule:
      interval: cron
      cronjob: 0 12 * * *
    reviewers:
      - akkinoc
    assignees:
      - akkinoc
    labels:
      - type:dependencies
    milestone: 2
    ignore:
      - dependency-name: kotlin.version
        versions: [ "[2.0,)" ]
