version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    labels:
      - type:enhancement
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - type:enhancement
