comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
formatting:
  ImportOrdering:
    active: true
  NoBlankLineBeforeRbrace:
    active: false
  ParameterListWrapping:
    indentSize: 8
style:
  ClassOrdering:
    active: true
  NoTabs:
    active: true
