name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    name: Build with Java ${{ matrix.java }}
    runs-on: ubuntu-24.04
    env:
      MAVEN_ARGS: -B --color always
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v5.0.0
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Export the project version
        run: echo PROJECT_VERSION=$(mvn -Dexpression=project.version -q help:evaluate) | tee -a $GITHUB_ENV
      - name: Build the project
        run: mvn clean install
      - name: Build the "examples/simple-java" project
        run: mvn -Dyaml-resource-bundle.version=$PROJECT_VERSION clean install
        working-directory: examples/simple-java
      - name: Build the "examples/simple-kotlin" project
        run: mvn -Dyaml-resource-bundle.version=$PROJECT_VERSION clean install
        working-directory: examples/simple-kotlin
      - name: Upload the coverage report to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
